# Generated by Django 3.1.4 on 2020-12-11 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_details',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_details', 'movie')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user_details', 'movie')},
        ),
    ]
